# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7NC-pV3SNiM3RD5gKO3SuSkyVhzsZsR
"""

import random
import string

def generate_password(length, use_upper, use_lower, use_numbers, use_special):
    characters = ""
    if use_upper:
        characters += string.ascii_uppercase
    if use_lower:
        characters += string.ascii_lowercase
    if use_numbers:
        characters += string.digits
    if use_special:
        characters += string.punctuation

    if not characters:
        return "Error: No character types selected."

    return ''.join(random.choice(characters) for _ in range(length))

def main():
    print("Password Generator")
    while True:
        try:
            length = int(input("\nEnter the desired password length: "))
            if length <= 0:
                print("Error: Password length must be greater than 0.")
                continue

            use_upper = input("Include uppercase letters? (yes/no): ").lower() == "yes"
            use_lower = input("Include lowercase letters? (yes/no): ").lower() == "yes"
            use_numbers = input("Include numbers? (yes/no): ").lower() == "yes"
            use_special = input("Include special characters? (yes/no): ").lower() == "yes"

            password = generate_password(length, use_upper, use_lower, use_numbers, use_special)
            print(f"\nGenerated Password: {password}")
        except ValueError:
            print("Error: Please enter a valid number for length.")

        again = input("Generate another password? (yes/no): ").lower()
        if again != "yes":
            print("Goodbye!")
            break

main()

